###################### GENERAL ####################
###################################################

userPoolId: ${userPoolId}
awsregion: us-east-1
enableSecurity: S
    
spring:  
  profiles:
    active: dev          
  aop:
    proxy-target-class: false


####PROFILE DEV
---
spring:
  profiles: dev
  application:
    name: mini_encuesta
    
  jpa:
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.MySQLDialect        
        ##dialect: org.hibernate.dialect.MySQL5InnoDBDialect       
        dialect: org.hibernate.dialect.MySQL5Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        naming_strategy:  org.hibernate.cfg.DefaultNamingStrategy        
        show_sql: true
        format_sql: true          
        packagesToScan: pe.jaav.sistemas.miniencuesta    
        id:
          new_generator_mappings: false
                
    hibernate:
      ddl-auto: none
  datasource:    
    driverClassName: com.mysql.jdbc.Driver    
    url: jdbc:mysql://${host}:${port}/${database}?useUnicode=true&characterEncoding=utf8&useSSL=false&requireSSL=false
    username: ${username}
    password: ${password}
 #Tunear parametros para reconección y tiempo fuera de conexión
    testOnBorrow: true
    #removeAbandonedTimeout: 1800
    #removeAbandoned: true    
    validation-query: SELECT 1 
    logAbandoned: true    
    validation-query-timeout: 30000 
    minEvictableIdleTimeMillis: 60000    
    maxWait: 60000
    maxIdle: 1
    minIdle: 0
    maxActive: 50
    initialSize: 1
    test-on-connect: true    
    
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
      
server:
  port: ${vcap.application.port:8081}      